os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^test.*$/"
  - "/^v.*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - DOCKERHUB='chalmersfsd'
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: KvgGKs/FqGElxd9KiSRViQnTZh85jcYK8zHeN2xa4Ej0fZEImiiYlBEjdNXtVsCxjmJ5Q9me0UfXqO/VBv2E3hHJG73Fv04odT4w/BthMjvJq0Xx42Ax6Dcpd3T296C5Bg0sFxe/xrjXRDBxmthKa6b2iuwEleR2hZG6TCAoSaVtH9P7RNlWcyBR/5KhoDE0OLzXL9v/pAuHfn6TTdxcLCnL+VW8NJd+pWlwNyhPkMUfB9RFGBemFYkFMxBytK4Age5dj+bqEu9B3IDjnbvIEzDpkxfXUDAcE0Scngd7krZsOY7yPFLWw/dIYEqQ5DaVnjTRCiahTehMoteX0TCOBxhdSvYzoMjQqZOZR32jWyfkFIeLBc6st08YF1M5eC/GgngrC03nKDAp0DrAb6ed31dOI818gZwagxT3uvoZPrjX3DvZyzFSD0A3CdGdGD2UFojZ5mCEgnArpauL1oRVmDq3pcB2n09RCjf1fdFb7ZDzKDdtbuRSwIAqjs8y25xEKBDyPFTr4lQBiIwghqXb/mV2F/Gd0IDs5p/MwpnI0JY7ArWfrgVhOVTE3Lsr78ANdhCQprXirPMvxK9BrGeWTxfI0Ev8wHRLmEpGbWZHiPyy7PTQmwgO1oddR2m68bE65vawGh025g+JyvDbbnAMInFZqWcPsWx33VfMG3jbg9Q=
  - secure: jZflb1TRcyX5prz49Wdn8yhoay0hzrTOMQARhsmPPfZ6XoCaJRuDUIY5cWnuT/27lRZcwGIRJf5jn7aXggqNP0cfXEdrWXjLA4frYYv3ljxFlKCTxz+z1TB3PH8+0lbJx+WTts24MtY86JhaTakTULRDbunz+EeR3fLiyTFotO5qgBs0gL92A4ufJ2XwgrC/IBXnAXizXvBYht2SY7MnnTNF7EoQYL8wo8c7uP/7m9A55QNT6vpe2sRIcb4/K2BpJbtDC0gLDFJjuRuAREIM8eczWa3hVCH3nthh7PTXtlbeWM4KkvGtM/ZOZA3PuPlmcSn3NlMoI1WIusZ1505/GTYu2xlY52YcuN+Z1OKoj+twY/M5tEYNqACrxK2i+3SdkOyD+pH7nvn1sTzPsdkoFSyN50VCJIgoqV+bmdm+oIjt0m54UDisM3Po72/ap0sW6ofdLiFJTPaxu8GlguyXFR50IWHOMAHU5vQk1OZaAJxRmpy2TKmVYnQTfICqHbuJeF1ducW+gHv41LfsnIbUPq5l38FP/eYlHu9Zd87m9lEGvCDQqDhZsEjqKYTCVJcfjEgYUcaNwvB9OY0OyMZmGN3xdcl1hjkWGaWHIEjLmaQF0u2mbaWhxjcUK/5dzsQaeAzFuEuvbOkAiTT4gSdNmNIcPBZLBNX1L3QO4MRO/3c=
install:
- docker build -f Dockerfile.amd64 -t ${IMAGE} .
script: skip
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- if [[ "${TRAVIS_BRANCH}" == *test* ]]; then docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER};
  docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}; echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}";
  else docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}; docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH};
  echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}"; fi
notifications:
  email:
    on_success: never
    on_failure: never
